---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: goldpinger
  labels:
    app.kubernetes.io/name: goldpinger
    app.kubernetes.io/component: server

rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list

...
