---
apiVersion: v1
kind: Service

metadata:
  name: goldpinger-server
  labels:
    app.kubernetes.io/name: goldpinger
    app.kubernetes.io/component: server

spec:
  selector:
    app.kubernetes.io/name: goldpinger
    app.kubernetes.io/component: server

  ports:
    - name: http
      port: 8080

...
